# <font color='blue'>Data Science Academy</font>

## <font color='blue'>Fundamentos de Linguagem Python Para Análise de Dados e Data Science</font>

## <font color='blue'>Capítulo 6 - Exercícios</font>

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

## Exercícios 

In [2]:
# Exercício 1 - Crie uma lista de 3 elementos e calcule a terceira potência de cada elemento.
lista=[1,2,3]
from numpy import power
cubo=power(lista,3)
print(cubo)

[ 1  8 27]


In [2]:
# Exercício 2 - Reescreva o código abaixo, usando a função map(). O resultado final deve ser o mesmo!
palavras = 'A Data Science Academy oferce os melhores cursos de análise de dados do Brasil.'.split()
resultado = [[w.upper(), w.lower(), len(w)] for w in palavras]
for i in resultado:
    print (i)

type(palavras)

['A', 'a', 1]
['DATA', 'data', 4]
['SCIENCE', 'science', 7]
['ACADEMY', 'academy', 7]
['OFERCE', 'oferce', 6]
['OS', 'os', 2]
['MELHORES', 'melhores', 8]
['CURSOS', 'cursos', 6]
['DE', 'de', 2]
['ANÁLISE', 'análise', 7]
['DE', 'de', 2]
['DADOS', 'dados', 5]
['DO', 'do', 2]
['BRASIL.', 'brasil.', 7]


list

A função map() em Python é uma função que aplica uma determinada função a cada elemento de uma estrutura de dados iterável (como uma lista, tupla ou outro objeto iterável). A função map() retorna um objeto que pode ser convertido em outra estrutura de dados, como uma lista, se necessário.

In [14]:
# Solução
#split por espaço, armazena numa lista
#for cada palavra em upper, lower case e it
#for para imprimir resultado

palavras = 'A Data Science Academy oferce os melhores cursos de análise de dados do Brasil.'.split()
resultado = list(map(lambda w: [w.upper(), w.lower(), len(w)], palavras))
for i in resultado:
    print (i)


['A', 'a', 1]
['DATA', 'data', 4]
['SCIENCE', 'science', 7]
['ACADEMY', 'academy', 7]
['OFERCE', 'oferce', 6]
['OS', 'os', 2]
['MELHORES', 'melhores', 8]
['CURSOS', 'cursos', 6]
['DE', 'de', 2]
['ANÁLISE', 'análise', 7]
['DE', 'de', 2]
['DADOS', 'dados', 5]
['DO', 'do', 2]
['BRASIL.', 'brasil.', 7]


In [16]:
# Exercício 3 - Calcule a matriz transposta da matriz abaixo.
# Caso não saiba o que é matriz transposta, visite este link: https://pt.wikipedia.org/wiki/Matriz_transposta
# Matriz transposta é um conceito fundamental na construção de redes neurais artificiais, base de sistemas de IA.
matrix = [[1, 2],[3,4],[5,6],[7,8]]

from numpy import transpose
mt=transpose(matrix)
print(mt)


[[1 3 5 7]
 [2 4 6 8]]


In [20]:
# Exercício 4 - Crie duas funções, uma para elevar um número ao quadrado e outra para elevar ao cubo. 
# Aplique as duas funções aos elementos da lista abaixo. 
# Obs: as duas funções devem ser aplicadas simultaneamente.
lista = [0, 1, 2, 3, 4]

def quadrado(x):
    return x**2

def cubo(x):
    return x**3

resultado_quadrado=list(map(quadrado,lista))
resultado_cubo=list(map(cubo,lista))
print(resultado_quadrado)
print(resultado_cubo)

[0, 1, 4, 9, 16]
[0, 1, 8, 27, 64]


In [23]:
# Exercício 5 - Abaixo você encontra duas listas. Faça com que cada elemento da listaA seja elevado 
# ao elemento correspondente na listaB.
listaA = [2, 3, 4]
listaB = [10, 11, 12]

list(map(lambda x, y: x**y, listaA,listaB))

[1024, 177147, 16777216]

In [26]:
# Exercício 6 - Considerando o range de valores abaixo, use a função filter() para retornar 
# apenas os valores negativos.
x=range(-5, 5)

list(filter(lambda x: x<0,range(-5,5)))

[-5, -4, -3, -2, -1]

A função filter() em Python é uma função que filtra elementos de uma estrutura de dados iterável (como uma lista, tupla ou outro objeto iterável) com base em uma determinada condição. A função filter() retorna um objeto filtro, que pode ser convertido em outra estrutura de dados, como uma lista, se necessário.

In [34]:
# Exercício 7 - Usando a função filter(), encontre os valores que são comuns às duas listas abaixo.
a = [1,2,3,5,7,9]
b = [2,3,5,6,7,8]

def comum(valor):
    return valor in a and valor in b

comuns=list(filter(comum, a))
print(comuns)

[2, 3, 5, 7]


In [35]:
a = [1,2,3,5,7,9]
b = [2,3,5,6,7,8]

list(filter(lambda valor: valor in a and valor in b, a))

[2, 3, 5, 7]

In [37]:
# Exercício 8 - Considere os dois dicionários abaixo. 
# Crie um terceiro dicionário com as chaves do dicionário 1 e os valores do dicionário 2.
dict1 = {'a':1,'b':2}
dict2 = {'c':4,'d':5}

dict(zip(dict1, dict2.values()))

{'a': 4, 'b': 5}

In [51]:
# Exercício 9 - Considere a lista abaixo e retorne apenas os elementos cujo índice for maior que 5.
lista = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

resultado = [elemento for indice, elemento in enumerate(lista) if indice > 5]
print(resultado)

['g', 'h']


In [59]:
# Exercício 10 - Crie um regex em Python para extrair a palavra que aparece depois das palavras 
# Data e Science na frase: 'A Data Science Academy oferce os melhores cursos de análise de dados do Brasil.'
import re

texto = "A Data Science Academy oferece os melhores cursos de análise de dados do Brasil"

padrao = r'Data Science (\w+)'

resultado = re.findall(padrao, texto)
print(resultado)

['Academy']


# Fim

### Obrigado

### Visite o Blog da Data Science Academy - <a href="http://blog.dsacademy.com.br">Blog DSA</a>